sudo: required
services:
    - docker

before_install:
    - docker build -t bogo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bogo/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-north-1-519777741374"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_ACCESS_KEY"